#include "common.h"

unsigned short reg_seg[]=
{
	Z0_OPTYPE_ES,
	Z0_OPTYPE_CS,
	Z0_OPTYPE_SS,
	Z0_OPTYPE_DS,
	Z0_OPTYPE_FS,
	Z0_OPTYPE_GS,
	Z0_OPTYPE_ERROR,
	Z0_OPTYPE_ERROR
};

unsigned short reg8[]=
{
	Z0_OPTYPE_AL,
	Z0_OPTYPE_CL,
	Z0_OPTYPE_DL,
	Z0_OPTYPE_BL,
	Z0_OPTYPE_AH,
	Z0_OPTYPE_CH,
	Z0_OPTYPE_DH,
	Z0_OPTYPE_BH
};

unsigned short reg16[]=
{
	Z0_OPTYPE_AX,
	Z0_OPTYPE_CX,
	Z0_OPTYPE_DX,
	Z0_OPTYPE_BX,
	Z0_OPTYPE_SP,
	Z0_OPTYPE_BP,
	Z0_OPTYPE_SI,
	Z0_OPTYPE_DI
};

unsigned short reg32[]=
{
	Z0_OPTYPE_EAX,
	Z0_OPTYPE_ECX,
	Z0_OPTYPE_EDX,
	Z0_OPTYPE_EBX,
	Z0_OPTYPE_ESP,
	Z0_OPTYPE_EBP,
	Z0_OPTYPE_ESI,
	Z0_OPTYPE_EDI
};

unsigned short reg16ptr[]=
{
	Z0_OPTYPE_PTR_BX_SI,
	Z0_OPTYPE_PTR_BX_DI,
	Z0_OPTYPE_PTR_BP_SI,
	Z0_OPTYPE_PTR_BP_DI,
	Z0_OPTYPE_PTR_SI,
	Z0_OPTYPE_PTR_DI,
	Z0_OPTYPE_PTR_BP,
	Z0_OPTYPE_PTR_BX
};

unsigned short reg32ptr[]=
{
	Z0_OPTYPE_PTR_EAX,
	Z0_OPTYPE_PTR_ECX,
	Z0_OPTYPE_PTR_EDX,
	Z0_OPTYPE_PTR_EBX,
	Z0_OPTYPE_PTR_ESP,
	Z0_OPTYPE_PTR_EBP,
	Z0_OPTYPE_PTR_ESI,
	Z0_OPTYPE_PTR_EDI
};

unsigned short reg_st[]=
{
	Z0_OPTYPE_ST0,
	Z0_OPTYPE_ST1,
	Z0_OPTYPE_ST2,
	Z0_OPTYPE_ST3,
	Z0_OPTYPE_ST4,
	Z0_OPTYPE_ST5,
	Z0_OPTYPE_ST6,
	Z0_OPTYPE_ST7
};

unsigned short reg_mm[]=
{
	Z0_OPTYPE_MM0,
	Z0_OPTYPE_MM1,
	Z0_OPTYPE_MM2,
	Z0_OPTYPE_MM3,
	Z0_OPTYPE_MM4,
	Z0_OPTYPE_MM5,
	Z0_OPTYPE_MM6,
	Z0_OPTYPE_MM7
};

unsigned short reg_xmm[]=
{
	Z0_OPTYPE_XMM0,
	Z0_OPTYPE_XMM1,
	Z0_OPTYPE_XMM2,
	Z0_OPTYPE_XMM3,
	Z0_OPTYPE_XMM4,
	Z0_OPTYPE_XMM5,
	Z0_OPTYPE_XMM6,
	Z0_OPTYPE_XMM7
};

unsigned short reg_scale[]=
{
	Z0_OPTYPE_NULL,
	Z0_OPTYPE_SCALE2,
	Z0_OPTYPE_SCALE4,
	Z0_OPTYPE_SCALE8
};

unsigned short reg_control[]=
{
	Z0_OPTYPE_CR0,
	Z0_OPTYPE_CR1,
	Z0_OPTYPE_CR2,
	Z0_OPTYPE_CR3,
	Z0_OPTYPE_CR4,
	Z0_OPTYPE_CR5,
	Z0_OPTYPE_CR6,
	Z0_OPTYPE_CR7
};

unsigned short reg_debug[]=
{
	Z0_OPTYPE_DR0,
	Z0_OPTYPE_DR1,
	Z0_OPTYPE_DR2,
	Z0_OPTYPE_DR3,
	Z0_OPTYPE_DR4,
	Z0_OPTYPE_DR5,
	Z0_OPTYPE_DR6,
	Z0_OPTYPE_DR7
};

unsigned short reg_test[]=
{
	Z0_OPTYPE_TR0,
	Z0_OPTYPE_TR1,
	Z0_OPTYPE_TR2,
	Z0_OPTYPE_TR3,
	Z0_OPTYPE_TR4,
	Z0_OPTYPE_TR5,
	Z0_OPTYPE_TR6,
	Z0_OPTYPE_TR7
};

Z0_OPCODE_TABLE opcode_base[] =
{
	{process_modrm, Z0_MNEMONIC_ADD,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ADD,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ADD,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ADD,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_ADD,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_ADD,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_ES,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_ES,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm, Z0_MNEMONIC_OR,		{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_OR,		{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_OR,		{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_OR,		{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_OR,		{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_OR,		{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_CS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ext0f, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm, Z0_MNEMONIC_ADC,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ADC,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ADC,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ADC,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_ADC,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_ADC,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_SS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_SS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm, Z0_MNEMONIC_SBB,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SBB,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SBB,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SBB,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_SBB,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_SBB,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_DS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_DS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm, Z0_MNEMONIC_AND,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_AND,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_AND,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_AND,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_AND,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_AND,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_DAA,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm, Z0_MNEMONIC_SUB,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SUB,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SUB,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SUB,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_SUB,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_SUB,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_DAS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm, Z0_MNEMONIC_XOR,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_XOR,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_XOR,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_XOR,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_XOR,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_XOR,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_AAA,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm, Z0_MNEMONIC_CMP,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_CMP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_CMP,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_CMP,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_CMP,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_CMP,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_AAS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_ECX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_EDX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_EBX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_ESP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_EBP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_ESI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_INC,	{Z0_OPTYPE_EDI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_ECX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_EDX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_EBX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_ESP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_EBP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_ESI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_DEC,	{Z0_OPTYPE_EDI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_ECX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_EDX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_EBX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_ESP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_EBP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_ESI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_EDI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_ECX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_EDX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_EBX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_ESP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_EBP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_ESI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POP,	{Z0_OPTYPE_EDI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_PUSHAD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_POPAD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_modrm,	Z0_MNEMONIC_BOUND,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm,	Z0_MNEMONIC_ARPL,	{Z0_OPTYPE_RM16,	Z0_OPTYPE_REG16,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_modrm,	Z0_MNEMONIC_IMUL,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_IMM32}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_IMM8SIGNED,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm,	Z0_MNEMONIC_IMUL,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_IMM8}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_INSB,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_INSD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_OUTSB,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_OUTSD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_JO,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JNO,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JC,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JNC,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JZ,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JNZ,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JBE,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JA,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JS,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JNS,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JP,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JNP,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JL,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JGE,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JLE,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JG,		{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm,	Z0_MNEMONIC_SET01,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SET01,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SET01,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SET01,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_TEST,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_TEST,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},

	{process_modrm, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG8,	Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_RM16,	Z0_OPTYPE_REG_SEGMENT,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG32},
	{process_modrm, Z0_MNEMONIC_LEA,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG_SEGMENT,	Z0_OPTYPE_RM16,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG32},
	{process_modrm, Z0_MNEMONIC_SET02,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},

	{process_basic,	Z0_MNEMONIC_NOP,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_ECX,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_EDX,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_EBX,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_ESP,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_EBP,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_ESI,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_XCHG,	{Z0_OPTYPE_EDI,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	
	{process_basic,	Z0_MNEMONIC_CWDE,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_CDQ,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_CALLF,	{Z0_OPTYPE_PTR16_32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_WAIT,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_PUSHFD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_POPFD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_SAHF,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_LAHF,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_ptr,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_AL,		Z0_OPTYPE_PTR32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_ptr,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_PTR32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_ptr,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_PTR32,	Z0_OPTYPE_AL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_ptr,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_PTR32,	Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic,	Z0_MNEMONIC_MOVSB,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_MOVSD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_CMPSB,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_CMPSD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_TEST,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_TEST,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_STOSB,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_STOSD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_LODSB,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_LODSD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_SCASB,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_SCASD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_CL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_DL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_BL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_AH,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_CH,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_DH,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_BH,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},

	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_ECX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_EDX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_EBX,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_ESP,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_EBP,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_ESI,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_MOV,	{Z0_OPTYPE_EDI,		Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_modrm, Z0_MNEMONIC_SET03,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SET03,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic,	Z0_MNEMONIC_RET,	{Z0_OPTYPE_IMM16,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_RET,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm, Z0_MNEMONIC_LES,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_LDS,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_SET04,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SET04,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},

	{process_basic, Z0_MNEMONIC_ENTER,	{Z0_OPTYPE_IMM16,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_LEAVE,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_RETF,	{Z0_OPTYPE_IMM16,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_RETF,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_INT3,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_INT,	{Z0_OPTYPE_IMM8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_INTO,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_IRET,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},

	{process_modrm,	Z0_MNEMONIC_SET03,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_1,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SET03,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_1,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SET03,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_CL_1,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SET03,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_CL_1,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_basic,	Z0_MNEMONIC_AAM,	{Z0_OPTYPE_IMM8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_AAD,	{Z0_OPTYPE_IMM8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_SETALC,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ptr,	Z0_MNEMONIC_XLAT,	{Z0_OPTYPE_EBX_PTR_1,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},

	{process_modrm,	Z0_MNEMONIC_ESC_D8,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm, Z0_MNEMONIC_ESC_D9,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm, Z0_MNEMONIC_ESC_DA,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm, Z0_MNEMONIC_ESC_DB,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},

	{process_modrm,	Z0_MNEMONIC_ESC_DC,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm, Z0_MNEMONIC_ESC_DD,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm, Z0_MNEMONIC_ESC_DE,	{Z0_OPTYPE_RM16PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm, Z0_MNEMONIC_ESC_DF,	{Z0_OPTYPE_RM16PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},

	{process_basic, Z0_MNEMONIC_LOOPNE,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_LOOPE,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_LOOP,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_JECXZ,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_IN,		{Z0_OPTYPE_AL,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_IN,		{Z0_OPTYPE_EAX,		Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_OUT,	{Z0_OPTYPE_IMM8,	Z0_OPTYPE_AL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_OUT,	{Z0_OPTYPE_IMM8,	Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_basic, Z0_MNEMONIC_CALL,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JMP,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_JMPF,	{Z0_OPTYPE_PTR16_32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JMPS,	{Z0_OPTYPE_REL8,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_IN,		{Z0_OPTYPE_AL,		Z0_OPTYPE_DX,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_IN,		{Z0_OPTYPE_EAX,		Z0_OPTYPE_DX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_OUT,	{Z0_OPTYPE_DX,		Z0_OPTYPE_AL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_OUT,	{Z0_OPTYPE_DX,		Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},

	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_ICE1,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_HLT,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_CMC,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm, Z0_MNEMONIC_ESC_F6,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ESC_F7,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},

	{process_basic, Z0_MNEMONIC_CLC,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_STC,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_CLI,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_STI,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_CLD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_STD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm, Z0_MNEMONIC_ESC_FE,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_ESC_FF,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
};

Z0_OPCODE_TABLE opcode_d8_11[] =
{
	{process_basic,	Z0_MNEMONIC_FADD,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FMUL,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOM,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOMP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSUB,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSUBR,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FDIV,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FDIVR,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_d9[] =
{
	{process_modrm,	Z0_MNEMONIC_FLD,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm,	Z0_MNEMONIC_FST,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FSTP,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FLDENV,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FLDCW,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FNSTENV,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FNSTCW,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
};

Z0_OPCODE_TABLE opcode_d9_11[] =
{
	{process_basic,	Z0_MNEMONIC_FLD,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FXCH,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSTP1,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_d9_11_2[] =
{
	{process_basic,	Z0_MNEMONIC_FNOP,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_d9_11_4[] =
{
	{process_basic,	Z0_MNEMONIC_FCHS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FABS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FTST,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FXAM,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_d9_11_5[] =
{
	{process_basic,	Z0_MNEMONIC_FLD1,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FLDL2T,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FLDL2E,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FLDPI,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FLDLG2,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FLDLN2,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FLDZ,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_d9_11_6[] =
{
	{process_basic,	Z0_MNEMONIC_F2XM1,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FYL2X,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FPTAN,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FPATAN,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FXTRACT,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FPREM1,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FDECSTP,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FINCSTP,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_d9_11_7[] =
{
	{process_basic,	Z0_MNEMONIC_FPREM,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FYL2XP1,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSQRT,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSINCOS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FRNDINT,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSCALE,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSIN,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_da_11[] =
{
	{process_basic,	Z0_MNEMONIC_FCMOVB,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCMOVE,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCMOVBE,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCMOVU,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_da_11_5[] =
{
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FUCOMPP,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_db[] =
{
	{process_modrm,	Z0_MNEMONIC_FILD,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FISTTP,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FIST,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FISTP,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm,	Z0_MNEMONIC_FLD,	{Z0_OPTYPE_RM80PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm,	Z0_MNEMONIC_FSTP,	{Z0_OPTYPE_RM80PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
};

Z0_OPCODE_TABLE opcode_db_11[] =
{
	{process_basic,	Z0_MNEMONIC_FCMOVNB,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCMOVNE,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCMOVNBE,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCMOVNU,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FUCOMI,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOMI,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_db_11_4[] =
{
	{process_basic,	Z0_MNEMONIC_FNENI,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FNDISI,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FNCLEX,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FNINIT,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_dc_11[] =
{
	{process_basic,	Z0_MNEMONIC_FADD,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FMUL,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOM2,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOMP3,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSUBR,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSUB,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FDIVR,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FDIV,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_dd[] =
{
	{process_modrm,	Z0_MNEMONIC_FLD,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FISTTP,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FST,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FSTP,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FRSTOR,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm,	Z0_MNEMONIC_FNSAVE,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FNSTSW,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
};

Z0_OPCODE_TABLE opcode_dd_11[] =
{
	{process_basic,	Z0_MNEMONIC_FFREE,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FXCH4,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FST,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSTP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FUCOM,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FUCOMP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_de_11[] =
{
	{process_basic,	Z0_MNEMONIC_FADDP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FMULP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOMP5,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSUBRP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSUBP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FDIVRP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FDIVP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_ST0,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_de_11_3[] =
{
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOMPP,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_df[] =
{
	{process_modrm,	Z0_MNEMONIC_FILD,	{Z0_OPTYPE_RM16PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FISTTP,	{Z0_OPTYPE_RM16,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FIST,	{Z0_OPTYPE_RM16PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FISTP,	{Z0_OPTYPE_RM16PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FBLD,	{Z0_OPTYPE_RM80PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FILD,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FBSTP,	{Z0_OPTYPE_RM80PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
	{process_modrm,	Z0_MNEMONIC_FISTP,	{Z0_OPTYPE_RM64PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_ST},
};

Z0_OPCODE_TABLE opcode_df_11[] =
{
	{process_basic,	Z0_MNEMONIC_FFREEP,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FXCH7,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSTP8,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FSTP9,	{Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_error,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FUCOMIP,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_basic,	Z0_MNEMONIC_FCOMIP,	{Z0_OPTYPE_ST0,		Z0_OPTYPE_REG_ST,	Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_df_11_4[] =
{
	{process_basic,	Z0_MNEMONIC_FNSTSW,	{Z0_OPTYPE_AX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_f6[] =
{
	{process_modrm,	Z0_MNEMONIC_TEST,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_TEST,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_IMM8,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_NOT,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_NEG,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_MUL,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_IMUL,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_DIV,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_IDIV,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
};

Z0_OPCODE_TABLE opcode_f7[] =
{
	{process_modrm,	Z0_MNEMONIC_TEST,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_TEST,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_IMM32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_NOT,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_NEG,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_MUL,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_IMUL,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_DIV,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_IDIV,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
};

Z0_OPCODE_TABLE opcode_fe[] =
{
	{process_modrm,	Z0_MNEMONIC_INC,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_DEC,	{Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_ff[] =
{
	{process_modrm,	Z0_MNEMONIC_INC,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_DEC,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CALL,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CALLF,	{Z0_OPTYPE_RM48PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm,	Z0_MNEMONIC_JMP,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_JMPF,	{Z0_OPTYPE_RM48PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm,	Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_RM32PTR,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};

Z0_OPCODE_TABLE opcode_ext0f[] =
{
// 0f 00
	{process_modrm, Z0_MNEMONIC_SET05,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_SET06,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_LAR,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG16},
	{process_modrm, Z0_MNEMONIC_LSL,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG16},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_CLTS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_INVD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_WBINVD,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_UD2,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm, Z0_MNEMONIC_PREFETCH,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_basic, Z0_MNEMONIC_FEMMS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
// 0f 10
	{process_modrm, Z0_MNEMONIC_MOVUPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM64,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_MOVUPS,	{Z0_OPTYPE_RM64,	Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_MOVLPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM64,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE | Z0_FLAG_MOD11_NO_PREFIX_OPERAND},
	{process_modrm, Z0_MNEMONIC_MOVLPS,	{Z0_OPTYPE_RM64,	Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_UNPCKLPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM64,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_UNPCKHPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM64,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOVHPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM64,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_PREFIX_REPE | Z0_FLAG_MOD11_NO_PREFIX_OPERAND},
	{process_modrm, Z0_MNEMONIC_MOVHPS,	{Z0_OPTYPE_RM64,	Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_SET07,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_NOP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_NOP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_NOP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_NOP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_NOP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_NOP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_NOP,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
// 0f 20
	{process_reg,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_REG_CONTROL,	Z0_OPTYPE_NULL}, 0},
	{process_reg,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_REG_DEBUG,	Z0_OPTYPE_NULL}, 0},
	{process_reg,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG_CONTROL,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, 0},
	{process_reg,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG_DEBUG,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, 0},
	{process_reg,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_REG_TEST,	Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_reg,	Z0_MNEMONIC_MOV,	{Z0_OPTYPE_REG_TEST,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm, Z0_MNEMONIC_MOVAPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_modrm, Z0_MNEMONIC_MOVAPS,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_modrm, Z0_MNEMONIC_CVTPI2PS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_MOVNTPS,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_CVTTPS2PI,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_CVTPS2PI,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_UCOMISS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_modrm, Z0_MNEMONIC_COMISS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
// 0f 30
	{process_basic, Z0_MNEMONIC_WRMSR,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_RDTSC,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_RDMSR,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_RDPMC,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_SYSENTER,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_SYSEXIT,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_basic, Z0_MNEMONIC_GETSEC,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ext38, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ext3a, Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
// 0f 40
	{process_modrm,	Z0_MNEMONIC_CMOVO,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVNO,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVC,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVNC,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVZ,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVNZ,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVBE,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVA,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVS,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVNS,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVP,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVNP,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVL,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVGE,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVLE,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMOVG,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
// 0f 50
	{process_modrm,	Z0_MNEMONIC_MOVMSKPS,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_NOT_MOD11_UD | Z0_OVERRIDE_REG_XMM | Z0_FLAG_NO_OPERAND_CONVERSION},
	{process_modrm, Z0_MNEMONIC_SQRTPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_RSQRTPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_RCPPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_ANDPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_modrm, Z0_MNEMONIC_ANDNPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_modrm, Z0_MNEMONIC_ORPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_modrm, Z0_MNEMONIC_XORPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_modrm, Z0_MNEMONIC_ADDPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_MULPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_CVTPS2PD,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_CVTDQ2PS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_SUBPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_MINPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_DIVPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_MAXPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
// 0f 60
	{process_modrm, Z0_MNEMONIC_PUNPCKLBW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PUNPCKLWD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PUNPCKLDQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PACKSSWB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PCMPGTB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PCMPGTW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PCMPGTD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PACKUSWB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PUNPCKHBW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PUNPCKHWD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PUNPCKHDQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PACKSSDW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_PUNPCKLQDQ,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_NOT_OPERAND_UD},
	{process_modrm, Z0_MNEMONIC_PUNPCKHQDQ,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_NOT_OPERAND_UD},
	{process_modrm, Z0_MNEMONIC_MOVD_1,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_NO_OPERAND_CONVERSION},
	{process_modrm, Z0_MNEMONIC_MOVQ_1,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_NO_OPERAND_CONVERSION | Z0_OVERRIDE_REG_MM | Z0_FLAG_PREFIX_REPE},
// 0f 70
	{process_modrm,	Z0_MNEMONIC_PSHUFW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_IMM8}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm,	Z0_MNEMONIC_PCMPEQB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PCMPEQW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PCMPEQD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_basic,	Z0_MNEMONIC_EMMS,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm,	Z0_MNEMONIC_VMREAD,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_VMWRITE,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
	{process_modrm, Z0_MNEMONIC_MOVD_2,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG_MM,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_NO_OPERAND_CONVERSION | Z0_FLAG_PREFIX_REPE},
	{process_modrm,	Z0_MNEMONIC_MOVQ_2,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG_MM,	Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM | Z0_FLAG_PREFIX_REPE},
// 0f 80
	{process_basic, Z0_MNEMONIC_JO,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JNO,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JC,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JNC,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JZ,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JNZ,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JBE,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JA,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JS,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JNS,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JP,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JNP,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JL,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JGE,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JLE,	{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic, Z0_MNEMONIC_JG,		{Z0_OPTYPE_REL32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND},
// 0f 90
	{process_modrm,	Z0_MNEMONIC_SETO,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETNO,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETC,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETNC,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETZ,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETNZ,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETBE,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETA,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETS,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETNS,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETP,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETNP,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETL,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETGE,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETLE,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SETG,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_ADDRESS},
// 0f a0
	{process_basic,	Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_FS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_POP,	{Z0_OPTYPE_FS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_CPUID,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_modrm,	Z0_MNEMONIC_BT,		{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SHLD,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_IMM8	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SHLD,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_CL_1	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_PUSH,	{Z0_OPTYPE_GS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_POP,	{Z0_OPTYPE_GS,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_RSM,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_modrm,	Z0_MNEMONIC_BTS,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SHRD,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_IMM8	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_SHRD,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_CL_1	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_ESC_0F_AE,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_modrm,	Z0_MNEMONIC_IMUL,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
// 0f b0
	{process_modrm,	Z0_MNEMONIC_CMPXCHG,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_CMPXCHG,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_LSS,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm,	Z0_MNEMONIC_BTR,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_LFS,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_LGS,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD},
	{process_modrm, Z0_MNEMONIC_MOVZX,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOVZX,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM16PTR,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_POPCNT,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_PREFIX_REPE},
	{process_modrm,	Z0_MNEMONIC_UD1,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_modrm,	Z0_MNEMONIC_BTC,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_BSF,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_BSR,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOVSX,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM8PTR,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_MOVSX,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM16PTR,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
// 0f c0
	{process_modrm, Z0_MNEMONIC_XADD,	{Z0_OPTYPE_RM8,		Z0_OPTYPE_REG8,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_XADD,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm, Z0_MNEMONIC_CMPPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_IMM8	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_MOVNTI,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG32,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_MOD11_UD | Z0_FLAG_NO_OPERAND_CONVERSION},
	{process_modrm, Z0_MNEMONIC_PINSRW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_IMM8	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG32 | Z0_FLAG_NO_OPERAND_CONVERSION},
	{process_modrm, Z0_MNEMONIC_PEXTRW,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_IMM8	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_MOD11_FIXED | Z0_FLAG_NO_OPERAND_CONVERSION | Z0_OVERRIDE_REG_MM},
	{process_modrm, Z0_MNEMONIC_SHUFPS,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_IMM8	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_EAX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_ECX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_EDX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_EBX,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_ESP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_EBP,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_ESI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
	{process_basic,	Z0_MNEMONIC_BSWAP,	{Z0_OPTYPE_EDI,		Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND},
// 0f d0
	{process_modrm,	Z0_MNEMONIC_ESC_0F_D0,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_NOT_OPERAND_UD | Z0_FLAG_PREFIX_REPNE},
	{process_modrm,	Z0_MNEMONIC_PSRLW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSRLD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSRLQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMULLW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_ESC_0F_D6,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_NOT_OPERAND_UD | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm, Z0_MNEMONIC_PMOVMSKB,	{Z0_OPTYPE_REG32,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_MOD11_FIXED | Z0_FLAG_NO_OPERAND_CONVERSION | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSUBUSB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSUBUSW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMINUB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PAND,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDUSB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDUSW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMAXUB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PANDN,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
// 0f e0
	{process_modrm,	Z0_MNEMONIC_PAVGB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSRAW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSRAD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PAVGW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMULHUW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMULHW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_ESC_0F_E6,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_XMM | Z0_FLAG_NOT_OPERAND_UD | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_PREFIX_REPE},
	{process_modrm,	Z0_MNEMONIC_MOVNTQ,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_REG_MM,	Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM | Z0_FLAG_MOD11_UD},
	{process_modrm,	Z0_MNEMONIC_PSUBSB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSUBSW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMINSW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_POR,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDSB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDSW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMAXSW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PXOR,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
// 0f f0
	{process_modrm,	Z0_MNEMONIC_ESC_0F_F0,	{Z0_OPTYPE_REG_XMM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS | Z0_FLAG_PREFIX_REPNE | Z0_FLAG_MOD11_UD},
	{process_modrm,	Z0_MNEMONIC_PSLLW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSLLD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSLLQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMULUDQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PMADDWD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSADBW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_MASKMOVQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM | Z0_FLAG_MOD11_FIXED},
	{process_modrm,	Z0_MNEMONIC_PSUBB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSUBW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSUBD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PSUBQ,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDW,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_modrm,	Z0_MNEMONIC_PADDD,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
};

Z0_OPCODE_TABLE opcode_0f_ae[] =
{
	{process_modrm,	Z0_MNEMONIC_FXSAVE,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_FXRSTOR,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_LDMXCSR,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_STMXCSR,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_XSAVE,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_modrm,	Z0_MNEMONIC_XRSTOR,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_modrm,	Z0_MNEMONIC_CLFLUSH,	{Z0_OPTYPE_RM32,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, Z0_FLAG_PREFIX_ADDRESS},
};

Z0_OPCODE_TABLE opcode_0f_ae_11[] =
{
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_LFENCE,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_MFENCE,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
	{process_basic,	Z0_MNEMONIC_SFENCE,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL	}, 0},
};

Z0_OPCODE_TABLE opcode_ext38[] =
{
	{process_modrm, Z0_MNEMONIC_PSHUFB,	{Z0_OPTYPE_REG_MM,	Z0_OPTYPE_RM32,		Z0_OPTYPE_NULL}, Z0_FLAG_PREFIX_OPERAND | Z0_FLAG_PREFIX_ADDRESS | Z0_OVERRIDE_REG_MM},
};

Z0_OPCODE_TABLE opcode_ext3a[] =
{
	{process_ud,	Z0_MNEMONIC_NULL,	{Z0_OPTYPE_NULL,	Z0_OPTYPE_NULL,		Z0_OPTYPE_NULL}, 0},
};
