#include <flcommon.h>

#define Z0_MAX_OPERANDS		3
#define Z0_MAX_OPCODE_LENGTH	16

typedef Z0_STATUS (__stdcall *Z0_DISASM)(struct Z0_DISASM_CONTEXT* context);

typedef enum
{
	Z0_DISASM_MODE_16 =1,
	Z0_DISASM_MODE_32,
	Z0_DISASM_MODE_64
};

typedef enum
{
	Z0_MNEMONIC_NULL =0,

	Z0_MNEMONIC_SET01,	// add or adc sbb and sub xor cmp
	Z0_MNEMONIC_SET02,	// pop
	Z0_MNEMONIC_SET03,	// rol ror rcl rcr shl shr sal sar
	Z0_MNEMONIC_SET04,	// mov
	Z0_MNEMONIC_SET05,	// sldt str lldt ltr verr verw
	Z0_MNEMONIC_SET06,	// smsw lmsw sgdt sidt lgdt lidt invlpg vmcall vmlaunch ...
	Z0_MNEMONIC_SET07,	// prefetchnta prefetcht0 prefetcht1 prefetcht2 nop
	Z0_MNEMONIC_SET_08,	// fadd fmul fcom fcomp fsub fsubr fdiv fdivr
	Z0_MNEMONIC_SET_09,	// fiadd fimul ficom ficomp fisub fisubr fidiv fidivr

	Z0_MNEMONIC_ESC_D8,
	Z0_MNEMONIC_ESC_D9,
	Z0_MNEMONIC_ESC_DA,
	Z0_MNEMONIC_ESC_DB,
	Z0_MNEMONIC_ESC_DC,
	Z0_MNEMONIC_ESC_DD,
	Z0_MNEMONIC_ESC_DE,
	Z0_MNEMONIC_ESC_DF,

	Z0_MNEMONIC_ESC_F6,	// test not neg mul imul div idiv
	Z0_MNEMONIC_ESC_F7,	// test not neg mul imul div idiv
	Z0_MNEMONIC_ESC_FE,	// inc dec
	Z0_MNEMONIC_ESC_FF,	// inc dec call callf jmp jmpf push

	Z0_MNEMONIC_ESC_0F_AE,	// fxsave fxrstor ...
	Z0_MNEMONIC_ESC_0F_D0,	// addsubpd addsubps
	Z0_MNEMONIC_ESC_0F_D6,	// movq movdq2q movq2dq
	Z0_MNEMONIC_ESC_0F_E6,	// cvttpd2dq cvtpd2dq cvtdq2pd
	Z0_MNEMONIC_ESC_0F_F0,	// lddqu

	Z0_MNEMONIC_AAA,
	Z0_MNEMONIC_AAD,
	Z0_MNEMONIC_AAM,
	Z0_MNEMONIC_AAS,
	Z0_MNEMONIC_DAA,
	Z0_MNEMONIC_DAS,

	Z0_MNEMONIC_ADC,
	Z0_MNEMONIC_ADD,
	Z0_MNEMONIC_AND,
	Z0_MNEMONIC_CMP,
	Z0_MNEMONIC_OR,
	Z0_MNEMONIC_SBB,
	Z0_MNEMONIC_SUB,
	Z0_MNEMONIC_XOR,

	Z0_MNEMONIC_CBW,
	Z0_MNEMONIC_CWDE,
	Z0_MNEMONIC_CWD,
	Z0_MNEMONIC_CDQ,

	Z0_MNEMONIC_CMPSB,
	Z0_MNEMONIC_CMPSW,
	Z0_MNEMONIC_CMPSD,

	Z0_MNEMONIC_MOVSB,
	Z0_MNEMONIC_MOVSW,
	Z0_MNEMONIC_MOVSD,

	Z0_MNEMONIC_LODSB,
	Z0_MNEMONIC_LODSW,
	Z0_MNEMONIC_LODSD,

	Z0_MNEMONIC_SCASB,
	Z0_MNEMONIC_SCASW,
	Z0_MNEMONIC_SCASD,

	Z0_MNEMONIC_STOSB,
	Z0_MNEMONIC_STOSW,
	Z0_MNEMONIC_STOSD,

	Z0_MNEMONIC_CMC,
	Z0_MNEMONIC_CLC,
	Z0_MNEMONIC_CLD,
	Z0_MNEMONIC_CLI,
	Z0_MNEMONIC_STC,
	Z0_MNEMONIC_STD,
	Z0_MNEMONIC_STI,

	Z0_MNEMONIC_HLT,

	Z0_MNEMONIC_CALL,
	Z0_MNEMONIC_CALLF,
	Z0_MNEMONIC_RET,
	Z0_MNEMONIC_RETF,
	Z0_MNEMONIC_JMP,
	Z0_MNEMONIC_JMPS,
	Z0_MNEMONIC_JMPF,
	Z0_MNEMONIC_INT,
	Z0_MNEMONIC_INT3,
	Z0_MNEMONIC_INTO,
	Z0_MNEMONIC_IRET,

	Z0_MNEMONIC_INC,
	Z0_MNEMONIC_DEC,

	Z0_MNEMONIC_PUSH,
	Z0_MNEMONIC_POP,
	Z0_MNEMONIC_PUSHA,
	Z0_MNEMONIC_PUSHAD,
	Z0_MNEMONIC_POPA,
	Z0_MNEMONIC_POPAD,
	Z0_MNEMONIC_PUSHF,
	Z0_MNEMONIC_PUSHFD,
	Z0_MNEMONIC_POPF,
	Z0_MNEMONIC_POPFD,

	Z0_MNEMONIC_ENTER,
	Z0_MNEMONIC_LEAVE,

	Z0_MNEMONIC_LAHF,
	Z0_MNEMONIC_SAHF,

	Z0_MNEMONIC_XLAT,
	Z0_MNEMONIC_XLATB,
	Z0_MNEMONIC_ARPL,
	Z0_MNEMONIC_BOUND,
	Z0_MNEMONIC_WAIT,
	Z0_MNEMONIC_NOP,

	Z0_MNEMONIC_JO,
	Z0_MNEMONIC_JNO,
	Z0_MNEMONIC_JC,
	Z0_MNEMONIC_JNC,
	Z0_MNEMONIC_JZ,
	Z0_MNEMONIC_JNZ,
	Z0_MNEMONIC_JBE,
	Z0_MNEMONIC_JA,
	Z0_MNEMONIC_JS,
	Z0_MNEMONIC_JNS,
	Z0_MNEMONIC_JP,
	Z0_MNEMONIC_JNP,
	Z0_MNEMONIC_JL,
	Z0_MNEMONIC_JGE,
	Z0_MNEMONIC_JLE,
	Z0_MNEMONIC_JG,

	Z0_MNEMONIC_JCXZ,
	Z0_MNEMONIC_JECXZ,

	Z0_MNEMONIC_LOOP,
	Z0_MNEMONIC_LOOPE,
	Z0_MNEMONIC_LOOPNE,

	Z0_MNEMONIC_SETO,
	Z0_MNEMONIC_SETNO,
	Z0_MNEMONIC_SETC,
	Z0_MNEMONIC_SETNC,
	Z0_MNEMONIC_SETZ,
	Z0_MNEMONIC_SETNZ,
	Z0_MNEMONIC_SETBE,
	Z0_MNEMONIC_SETA,
	Z0_MNEMONIC_SETS,
	Z0_MNEMONIC_SETNS,
	Z0_MNEMONIC_SETP,
	Z0_MNEMONIC_SETNP,
	Z0_MNEMONIC_SETL,
	Z0_MNEMONIC_SETGE,
	Z0_MNEMONIC_SETLE,
	Z0_MNEMONIC_SETG,

	Z0_MNEMONIC_CMOVO,
	Z0_MNEMONIC_CMOVNO,
	Z0_MNEMONIC_CMOVC,
	Z0_MNEMONIC_CMOVNC,
	Z0_MNEMONIC_CMOVZ,
	Z0_MNEMONIC_CMOVNZ,
	Z0_MNEMONIC_CMOVBE,
	Z0_MNEMONIC_CMOVA,
	Z0_MNEMONIC_CMOVS,
	Z0_MNEMONIC_CMOVNS,
	Z0_MNEMONIC_CMOVP,
	Z0_MNEMONIC_CMOVNP,
	Z0_MNEMONIC_CMOVL,
	Z0_MNEMONIC_CMOVGE,
	Z0_MNEMONIC_CMOVLE,
	Z0_MNEMONIC_CMOVG,

	Z0_MNEMONIC_SETALC,

	Z0_MNEMONIC_MOV,
	Z0_MNEMONIC_LEA,
	Z0_MNEMONIC_MOVSX,
	Z0_MNEMONIC_MOVZX,
	Z0_MNEMONIC_XCHG,
	Z0_MNEMONIC_BSWAP,

	Z0_MNEMONIC_CMPXCHG,
	Z0_MNEMONIC_CMPXCHG8B,

	Z0_MNEMONIC_DIV,
	Z0_MNEMONIC_MUL,
	Z0_MNEMONIC_IDIV,
	Z0_MNEMONIC_IMUL,

	Z0_MNEMONIC_NEG,
	Z0_MNEMONIC_NOT,
	Z0_MNEMONIC_TEST,

	Z0_MNEMONIC_SAL,
	Z0_MNEMONIC_SAR,
	Z0_MNEMONIC_SHL,
	Z0_MNEMONIC_SHR,

	Z0_MNEMONIC_ROL,
	Z0_MNEMONIC_ROR,
	Z0_MNEMONIC_RCL,
	Z0_MNEMONIC_RCR,

	Z0_MNEMONIC_SHLD,
	Z0_MNEMONIC_SHRD,

	Z0_MNEMONIC_IN,
	Z0_MNEMONIC_OUT,
	Z0_MNEMONIC_INSB,
	Z0_MNEMONIC_INSW,
	Z0_MNEMONIC_INSD,
	Z0_MNEMONIC_OUTSB,
	Z0_MNEMONIC_OUTSW,
	Z0_MNEMONIC_OUTSD,

	Z0_MNEMONIC_LES,
	Z0_MNEMONIC_LDS,
	Z0_MNEMONIC_LSS,
	Z0_MNEMONIC_LFS,
	Z0_MNEMONIC_LGS,

	Z0_MNEMONIC_XADD,

	Z0_MNEMONIC_SLDT,
	Z0_MNEMONIC_STR,
	Z0_MNEMONIC_LLDT,
	Z0_MNEMONIC_LTR,
	Z0_MNEMONIC_VERR,
	Z0_MNEMONIC_VERW,
	Z0_MNEMONIC_SGDT,
	Z0_MNEMONIC_SIDT,
	Z0_MNEMONIC_LGDT,
	Z0_MNEMONIC_LIDT,
	Z0_MNEMONIC_SMSW,
	Z0_MNEMONIC_LMSW,
	Z0_MNEMONIC_INVLPG,

	Z0_MNEMONIC_LAR,
	Z0_MNEMONIC_LSL,
	Z0_MNEMONIC_CLTS,
	Z0_MNEMONIC_INVD,
	Z0_MNEMONIC_WBINVD,

	Z0_MNEMONIC_VMCALL,
	Z0_MNEMONIC_VMLAUNCH,
	Z0_MNEMONIC_VMRESUME,
	Z0_MNEMONIC_VMXOFF,
	Z0_MNEMONIC_MONITOR,
	Z0_MNEMONIC_MWAIT,
	Z0_MNEMONIC_XGETBV,
	Z0_MNEMONIC_XSETBV,
	Z0_MNEMONIC_VMRUN,
	Z0_MNEMONIC_VMMCALL,
	Z0_MNEMONIC_VMLOAD,
	Z0_MNEMONIC_VMSAVE,
	Z0_MNEMONIC_STGI,
	Z0_MNEMONIC_CLGI,
	Z0_MNEMONIC_SKINIT,
	Z0_MNEMONIC_INVLPGA,
	Z0_MNEMONIC_RDTSCP,
	Z0_MNEMONIC_VMPTRLD,
	Z0_MNEMONIC_VMCLEAR,
	Z0_MNEMONIC_VMPTRST,

	Z0_MNEMONIC_VMREAD,
	Z0_MNEMONIC_VMWRITE,

	Z0_MNEMONIC_FADD,
	Z0_MNEMONIC_FMUL,
	Z0_MNEMONIC_FCOM,
	Z0_MNEMONIC_FCOMP,
	Z0_MNEMONIC_FCOM2,
	Z0_MNEMONIC_FCOMP3,
	Z0_MNEMONIC_FSUB,
	Z0_MNEMONIC_FSUBR,
	Z0_MNEMONIC_FDIV,
	Z0_MNEMONIC_FDIVR,
	Z0_MNEMONIC_FLD,
	Z0_MNEMONIC_FIADD,
	Z0_MNEMONIC_FILD,
	Z0_MNEMONIC_FXCH,
	Z0_MNEMONIC_FSTP1,
	Z0_MNEMONIC_FCHS,
	Z0_MNEMONIC_FABS,
	Z0_MNEMONIC_FTST,
	Z0_MNEMONIC_FXAM,
	Z0_MNEMONIC_FLD1,
	Z0_MNEMONIC_FLDL2T,
	Z0_MNEMONIC_FLDL2E,
	Z0_MNEMONIC_FLDPI,
	Z0_MNEMONIC_FLDLG2,
	Z0_MNEMONIC_FLDLN2,
	Z0_MNEMONIC_FLDZ,
	Z0_MNEMONIC_F2XM1,
	Z0_MNEMONIC_FYL2X,
	Z0_MNEMONIC_FPTAN,
	Z0_MNEMONIC_FPATAN,
	Z0_MNEMONIC_FXTRACT,
	Z0_MNEMONIC_FPREM1,
	Z0_MNEMONIC_FDECSTP,
	Z0_MNEMONIC_FINCSTP,
	Z0_MNEMONIC_FPREM,
	Z0_MNEMONIC_FYL2XP1,
	Z0_MNEMONIC_FSQRT,
	Z0_MNEMONIC_FSINCOS,
	Z0_MNEMONIC_FRNDINT,
	Z0_MNEMONIC_FSCALE,
	Z0_MNEMONIC_FSIN,
	Z0_MNEMONIC_FCOS,
	Z0_MNEMONIC_FST,
	Z0_MNEMONIC_FSTP,
	Z0_MNEMONIC_FLDENV,
	Z0_MNEMONIC_FLDCW,
	Z0_MNEMONIC_FNSTENV,
	Z0_MNEMONIC_FNSTCW,
	Z0_MNEMONIC_FNOP,
	Z0_MNEMONIC_FCMOVB,
	Z0_MNEMONIC_FCMOVE,
	Z0_MNEMONIC_FCMOVBE,
	Z0_MNEMONIC_FCMOVU,
	Z0_MNEMONIC_FIMUL,
	Z0_MNEMONIC_FICOM,
	Z0_MNEMONIC_FICOMP,
	Z0_MNEMONIC_FISUB,
	Z0_MNEMONIC_FISUBR,
	Z0_MNEMONIC_FIDIV,
	Z0_MNEMONIC_FIDIVR,
	Z0_MNEMONIC_FUCOMP,
	Z0_MNEMONIC_FUCOMPP,
	Z0_MNEMONIC_FISTTP,
	Z0_MNEMONIC_FIST,
	Z0_MNEMONIC_FISTP,
	Z0_MNEMONIC_FCMOVNB,
	Z0_MNEMONIC_FCMOVNE,
	Z0_MNEMONIC_FCMOVNBE,
	Z0_MNEMONIC_FCMOVNU,
	Z0_MNEMONIC_FNENI,
	Z0_MNEMONIC_FUCOMI,
	Z0_MNEMONIC_FCOMI,
	Z0_MNEMONIC_FNDISI,
	Z0_MNEMONIC_FNCLEX,
	Z0_MNEMONIC_FNINIT,
	Z0_MNEMONIC_FFREE,
	Z0_MNEMONIC_FXCH4,
	Z0_MNEMONIC_FUCOM,
	Z0_MNEMONIC_FRSTOR,
	Z0_MNEMONIC_FNSAVE,
	Z0_MNEMONIC_FNSTSW,
	Z0_MNEMONIC_FADDP,
	Z0_MNEMONIC_FMULP,
	Z0_MNEMONIC_FCOMP5,
	Z0_MNEMONIC_FSUBRP,
	Z0_MNEMONIC_FSUBP,
	Z0_MNEMONIC_FDIVRP,
	Z0_MNEMONIC_FDIVP,
	Z0_MNEMONIC_FCOMPP,
	Z0_MNEMONIC_FFREEP,
	Z0_MNEMONIC_FXCH7,
	Z0_MNEMONIC_FSTP8,
	Z0_MNEMONIC_FSTP9,
	Z0_MNEMONIC_FUCOMIP,
	Z0_MNEMONIC_FCOMIP,
	Z0_MNEMONIC_FBLD,
	Z0_MNEMONIC_FBSTP,

	Z0_MNEMONIC_PREFETCH,
	Z0_MNEMONIC_PREFETCHNTA,
	Z0_MNEMONIC_PREFETCHT0,
	Z0_MNEMONIC_PREFETCHT1,
	Z0_MNEMONIC_PREFETCHT2,
	Z0_MNEMONIC_EMMS,
	Z0_MNEMONIC_FEMMS,
	Z0_MNEMONIC_3D,

	Z0_MNEMONIC_MOVD_1,
	Z0_MNEMONIC_MOVD_2,
	Z0_MNEMONIC_MOVD_3,
	Z0_MNEMONIC_MOVQ_1,
	Z0_MNEMONIC_MOVQ_2,
	Z0_MNEMONIC_MOVQ_3,
	Z0_MNEMONIC_MOVDQA,
	Z0_MNEMONIC_MOVDQU,
	Z0_MNEMONIC_MOVDQ2Q,
	Z0_MNEMONIC_MOVQ2DQ,

	Z0_MNEMONIC_MOVNTPD,
	Z0_MNEMONIC_MOVNTPS,
	Z0_MNEMONIC_MOVNTSD,
	Z0_MNEMONIC_MOVNTSS,
	Z0_MNEMONIC_MOVNTQ,
	Z0_MNEMONIC_MOVNTDQ,

	Z0_MNEMONIC_MOVAPD,
	Z0_MNEMONIC_MOVAPS,
	Z0_MNEMONIC_MOVUPD,
	Z0_MNEMONIC_MOVUPS,
	Z0_MNEMONIC_MOVLPD,
	Z0_MNEMONIC_MOVLPS,
	Z0_MNEMONIC_UNPCKLPD,
	Z0_MNEMONIC_UNPCKLPS,
	Z0_MNEMONIC_UNPCKHPD,
	Z0_MNEMONIC_UNPCKHPS,
	Z0_MNEMONIC_MOVHPD,
	Z0_MNEMONIC_MOVHPS,
	Z0_MNEMONIC_MOVHLPS,
	Z0_MNEMONIC_MOVLHPS,
	Z0_MNEMONIC_MOVSD_,
	Z0_MNEMONIC_MOVSS,
	Z0_MNEMONIC_MOVDDUP,
	Z0_MNEMONIC_MOVSLDUP,
	Z0_MNEMONIC_MOVSHDUP,

	Z0_MNEMONIC_CVTDQ2PS,
	Z0_MNEMONIC_CVTDQ2PD,
	Z0_MNEMONIC_CVTPD2DQ,
	Z0_MNEMONIC_CVTPD2PI,
	Z0_MNEMONIC_CVTPD2PS,
	Z0_MNEMONIC_CVTPI2PS,
	Z0_MNEMONIC_CVTPI2PD,
	Z0_MNEMONIC_CVTPS2DQ,
	Z0_MNEMONIC_CVTPS2PD,
	Z0_MNEMONIC_CVTPS2PI,
	Z0_MNEMONIC_CVTSD2SI,
	Z0_MNEMONIC_CVTSD2SS,
	Z0_MNEMONIC_CVTSI2SD,
	Z0_MNEMONIC_CVTSI2SS,
	Z0_MNEMONIC_CVTSS2SD,
	Z0_MNEMONIC_CVTSS2SI,
	Z0_MNEMONIC_CVTTPD2DQ,
	Z0_MNEMONIC_CVTTPD2PI,
	Z0_MNEMONIC_CVTTPS2DQ,
	Z0_MNEMONIC_CVTTPS2PI,
	Z0_MNEMONIC_CVTTSD2SI,
	Z0_MNEMONIC_CVTTSS2SI,

	Z0_MNEMONIC_UCOMISS,
	Z0_MNEMONIC_UCOMISD,
	Z0_MNEMONIC_COMISS,
	Z0_MNEMONIC_COMISD,

	Z0_MNEMONIC_MOVMSKPS,
	Z0_MNEMONIC_MOVMSKPD,

	Z0_MNEMONIC_SQRTPS,
	Z0_MNEMONIC_SQRTPD,
	Z0_MNEMONIC_SQRTSS,
	Z0_MNEMONIC_SQRTSD,
	Z0_MNEMONIC_RSQRTPS,
	Z0_MNEMONIC_RSQRTSS,
	Z0_MNEMONIC_RCPPS,
	Z0_MNEMONIC_RCPSS,

	Z0_MNEMONIC_ANDPS,
	Z0_MNEMONIC_ANDPD,
	Z0_MNEMONIC_ANDNPS,
	Z0_MNEMONIC_ANDNPD,
	Z0_MNEMONIC_ORPS,
	Z0_MNEMONIC_ORPD,
	Z0_MNEMONIC_XORPS,
	Z0_MNEMONIC_XORPD,

	Z0_MNEMONIC_ADDPS,
	Z0_MNEMONIC_ADDPD,
	Z0_MNEMONIC_ADDSS,
	Z0_MNEMONIC_ADDSD,

	Z0_MNEMONIC_MULPS,
	Z0_MNEMONIC_MULPD,
	Z0_MNEMONIC_MULSS,
	Z0_MNEMONIC_MULSD,

	Z0_MNEMONIC_SUBPS,
	Z0_MNEMONIC_SUBPD,
	Z0_MNEMONIC_SUBSS,
	Z0_MNEMONIC_SUBSD,

	Z0_MNEMONIC_MINPS,
	Z0_MNEMONIC_MINPD,
	Z0_MNEMONIC_MINSS,
	Z0_MNEMONIC_MINSD,

	Z0_MNEMONIC_DIVPS,
	Z0_MNEMONIC_DIVPD,
	Z0_MNEMONIC_DIVSS,
	Z0_MNEMONIC_DIVSD,

	Z0_MNEMONIC_MAXPS,
	Z0_MNEMONIC_MAXPD,
	Z0_MNEMONIC_MAXSS,
	Z0_MNEMONIC_MAXSD,

	Z0_MNEMONIC_CPUID,
	Z0_MNEMONIC_RSM,
	Z0_MNEMONIC_FXSAVE,
	Z0_MNEMONIC_FXRSTOR,
	Z0_MNEMONIC_LDMXCSR,
	Z0_MNEMONIC_STMXCSR,
	Z0_MNEMONIC_XSAVE,
	Z0_MNEMONIC_XRSTOR,
	Z0_MNEMONIC_CLFLUSH,

	Z0_MNEMONIC_BT,
	Z0_MNEMONIC_BTS,
	Z0_MNEMONIC_BTR,
	Z0_MNEMONIC_BTC,
	Z0_MNEMONIC_BSF,
	Z0_MNEMONIC_BSR,

	Z0_MNEMONIC_TZCNT,
	Z0_MNEMONIC_LZCNT,

	Z0_MNEMONIC_SYSENTER,
	Z0_MNEMONIC_SYSEXIT,
	Z0_MNEMONIC_WRMSR,
	Z0_MNEMONIC_RDTSC,
	Z0_MNEMONIC_RDMSR,
	Z0_MNEMONIC_RDPMC,

	Z0_MNEMONIC_GETSEC,

	Z0_MNEMONIC_PAVGB,
	Z0_MNEMONIC_PSRAW,
	Z0_MNEMONIC_PSRAD,
	Z0_MNEMONIC_PAVGW,
	Z0_MNEMONIC_PMULHUW,
	Z0_MNEMONIC_PMULHW,
	Z0_MNEMONIC_PSUBSB,
	Z0_MNEMONIC_PSUBSW,
	Z0_MNEMONIC_PMINSW,
	Z0_MNEMONIC_POR,
	Z0_MNEMONIC_PADDSB,
	Z0_MNEMONIC_PADDSW,
	Z0_MNEMONIC_PMAXSW,
	Z0_MNEMONIC_PXOR,

	Z0_MNEMONIC_PSRLW,
	Z0_MNEMONIC_PSRLD,
	Z0_MNEMONIC_PSRLQ,
	Z0_MNEMONIC_PADDQ,
	Z0_MNEMONIC_PMULLW,
	Z0_MNEMONIC_PMOVMSKB,
	Z0_MNEMONIC_PADDSUSW,

	Z0_MNEMONIC_PUNPCKLBW,
	Z0_MNEMONIC_PUNPCKLWD,
	Z0_MNEMONIC_PUNPCKLDQ,
	Z0_MNEMONIC_PACKSSWB,
	Z0_MNEMONIC_PACKUSWB,
	Z0_MNEMONIC_PUNPCKHBW,
	Z0_MNEMONIC_PUNPCKHWD,
	Z0_MNEMONIC_PUNPCKHDQ,
	Z0_MNEMONIC_PACKSSDW,
	Z0_MNEMONIC_PUNPCKLQDQ,
	Z0_MNEMONIC_PUNPCKHQDQ,

	Z0_MNEMONIC_PSHUFW,
	Z0_MNEMONIC_PSHUFD,
	Z0_MNEMONIC_PSHUFLW,
	Z0_MNEMONIC_PSHUFHW,

	Z0_MNEMONIC_PSHUFB,
	Z0_MNEMONIC_PHADDW,
	Z0_MNEMONIC_PHADDD,
	Z0_MNEMONIC_PHADDSW,
	Z0_MNEMONIC_PMADDUBSW,
	Z0_MNEMONIC_PHSUBW,
	Z0_MNEMONIC_PHSUBD,
	Z0_MNEMONIC_PHSUBSW,
	Z0_MNEMONIC_PSIGNB,
	Z0_MNEMONIC_PSIGNW,
	Z0_MNEMONIC_PSIGND,
	Z0_MNEMONIC_PMULHRSW,

	Z0_MNEMONIC_PBLENDVB,
	Z0_MNEMONIC_BLENDVPS,
	Z0_MNEMONIC_BLENDVPD,
	Z0_MNEMONIC_PTEST,
	Z0_MNEMONIC_PABSB,
	Z0_MNEMONIC_PABSW,
	Z0_MNEMONIC_PABSD,
	Z0_MNEMONIC_PMOVSXBW,
	Z0_MNEMONIC_PMOVSXBD,
	Z0_MNEMONIC_PMOVSXBQ,
	Z0_MNEMONIC_PMOVSXWD,
	Z0_MNEMONIC_PMOVSXWQ,
	Z0_MNEMONIC_PMOVSXDQ,
	Z0_MNEMONIC_PMULDQ,
	Z0_MNEMONIC_MOVNTDQA,
	Z0_MNEMONIC_PACKUSDW,
	Z0_MNEMONIC_PMOVZXBW,
	Z0_MNEMONIC_PMOVZXBD,
	Z0_MNEMONIC_PMOVZXBQ,
	Z0_MNEMONIC_PMOVZXWD,
	Z0_MNEMONIC_PMOVZXWQ,
	Z0_MNEMONIC_PMOVZXDQ,
	Z0_MNEMONIC_PMINSB,
	Z0_MNEMONIC_PMINSD,
	Z0_MNEMONIC_PMINUW,
	Z0_MNEMONIC_PMINUD,
	Z0_MNEMONIC_PMAXSB,
	Z0_MNEMONIC_PMAXSD,
	Z0_MNEMONIC_PMAXUW,
	Z0_MNEMONIC_PMAXUD,
	Z0_MNEMONIC_PMULLD,
	Z0_MNEMONIC_PHMINPOSUW,

	Z0_MNEMONIC_PSLLW,
	Z0_MNEMONIC_PSLLD,
	Z0_MNEMONIC_PSLLQ,
	Z0_MNEMONIC_PMULUDQ,
	Z0_MNEMONIC_PMADDWD,
	Z0_MNEMONIC_PSADBW,
	Z0_MNEMONIC_MASKMOVDQU,
	Z0_MNEMONIC_MASKMOVQ,
	Z0_MNEMONIC_PSUBB,
	Z0_MNEMONIC_PSUBW,
	Z0_MNEMONIC_PSUBD,
	Z0_MNEMONIC_PSUBQ,
	Z0_MNEMONIC_PADDB,
	Z0_MNEMONIC_PADDW,
	Z0_MNEMONIC_PADDD,

	Z0_MNEMONIC_PSUBUSB,
	Z0_MNEMONIC_PSUBUSW,
	Z0_MNEMONIC_PMINUB,
	Z0_MNEMONIC_PAND,
	Z0_MNEMONIC_PADDUSB,
	Z0_MNEMONIC_PADDUSW,
	Z0_MNEMONIC_PMAXUB,
	Z0_MNEMONIC_PANDN,

	Z0_MNEMONIC_PCMPEQB,
	Z0_MNEMONIC_PCMPEQW,
	Z0_MNEMONIC_PCMPEQD,
	Z0_MNEMONIC_PCMPEQQ,
	
	Z0_MNEMONIC_PCMPGTB,
	Z0_MNEMONIC_PCMPGTW,
	Z0_MNEMONIC_PCMPGTD,
	Z0_MNEMONIC_PCMPGTQ,

	Z0_MNEMONIC_EXTRQ,

	Z0_MNEMONIC_INVEPT,
	Z0_MNEMONIC_INVVPID,

	Z0_MNEMONIC_AESIMC,
	Z0_MNEMONIC_AESENC,
	Z0_MNEMONIC_AESENCLAST,
	Z0_MNEMONIC_AESDEC,
	Z0_MNEMONIC_AESDECLAST,
	Z0_MNEMONIC_AESKEYGENASSIST,

	Z0_MNEMONIC_LFENCE,
	Z0_MNEMONIC_MFENCE,
	Z0_MNEMONIC_SFENCE,

	Z0_MNEMONIC_POPCNT,

	Z0_MNEMONIC_CMPPS,

	Z0_MNEMONIC_CMPEQPS,
	Z0_MNEMONIC_CMPLTPS,
	Z0_MNEMONIC_CMPLEPS,
	Z0_MNEMONIC_CMPUNORDPS,
	Z0_MNEMONIC_CMPNEQPS,
	Z0_MNEMONIC_CMPNLTPS,
	Z0_MNEMONIC_CMPNLEPS,
	Z0_MNEMONIC_CMPORDPS,

	Z0_MNEMONIC_CMPEQPD,
	Z0_MNEMONIC_CMPLTPD,
	Z0_MNEMONIC_CMPLEPD,
	Z0_MNEMONIC_CMPUNORDPD,
	Z0_MNEMONIC_CMPNEQPD,
	Z0_MNEMONIC_CMPNLTPD,
	Z0_MNEMONIC_CMPNLEPD,
	Z0_MNEMONIC_CMPORDPD,

	Z0_MNEMONIC_CMPEQSD,
	Z0_MNEMONIC_CMPLTSD,
	Z0_MNEMONIC_CMPLESD,
	Z0_MNEMONIC_CMPUNORDSD,
	Z0_MNEMONIC_CMPNEQSD,
	Z0_MNEMONIC_CMPNLTSD,
	Z0_MNEMONIC_CMPNLESD,
	Z0_MNEMONIC_CMPORDSD,

	Z0_MNEMONIC_CMPEQSS,
	Z0_MNEMONIC_CMPLTSS,
	Z0_MNEMONIC_CMPLESS,
	Z0_MNEMONIC_CMPUNORDSS,
	Z0_MNEMONIC_CMPNEQSS,
	Z0_MNEMONIC_CMPNLTSS,
	Z0_MNEMONIC_CMPNLESS,
	Z0_MNEMONIC_CMPORDSS,

	Z0_MNEMONIC_MOVNTI,

	Z0_MNEMONIC_PINSRB,
	Z0_MNEMONIC_PINSRW,
	Z0_MNEMONIC_PINSRD,
	Z0_MNEMONIC_PINSRQ,

	Z0_MNEMONIC_PEXTRB,
	Z0_MNEMONIC_PEXTRW,
	Z0_MNEMONIC_PEXTRD,
	Z0_MNEMONIC_PEXTRQ,

	Z0_MNEMONIC_SHUFPS,
	Z0_MNEMONIC_SHUFPD,

	Z0_MNEMONIC_ADDSUBPS,
	Z0_MNEMONIC_ADDSUBPD,

	Z0_MNEMONIC_LDDQU,

	Z0_MNEMONIC_ICE1,

	Z0_PREFIX_ES,
	Z0_PREFIX_CS,
	Z0_PREFIX_SS,
	Z0_PREFIX_DS,
	Z0_PREFIX_FS,
	Z0_PREFIX_GS,

	Z0_PREFIX_OPERAND,
	Z0_PREFIX_ADDRESS,
	Z0_PREFIX_LOCK,
	Z0_PREFIX_REPNE,
	Z0_PREFIX_REPE,

	Z0_MNEMONIC_UD,
	Z0_MNEMONIC_UD1,
	Z0_MNEMONIC_UD2,

	Z0_MNEMONIC_LAST
};

typedef enum
{
	Z0_OPTYPE_NULL =0,

	Z0_OPTYPE_IMM8,
	Z0_OPTYPE_IMM8SIGNED,
	Z0_OPTYPE_PTR8,
	Z0_OPTYPE_REL8,

	Z0_OPTYPE_IMM16,
	Z0_OPTYPE_PTR16,
	Z0_OPTYPE_REL16,

	Z0_OPTYPE_IMM32,
	Z0_OPTYPE_PTR32,
	Z0_OPTYPE_REL32,

	Z0_OPTYPE_RM8,
	Z0_OPTYPE_RM8PTR,
	Z0_OPTYPE_RM16,
	Z0_OPTYPE_RM16PTR,
	Z0_OPTYPE_RM32,
	Z0_OPTYPE_RM32PTR,
	Z0_OPTYPE_RM48,
	Z0_OPTYPE_RM48PTR,
	Z0_OPTYPE_RM64,
	Z0_OPTYPE_RM64PTR,
	Z0_OPTYPE_RM80,
	Z0_OPTYPE_RM80PTR,

	Z0_OPTYPE_PTR16_16,
	Z0_OPTYPE_PTR16_32,

	Z0_OPTYPE_REG8,
	Z0_OPTYPE_REG16,
	Z0_OPTYPE_REG32,
	Z0_OPTYPE_REG_SEGMENT,
	Z0_OPTYPE_REG_CONTROL,
	Z0_OPTYPE_REG_DEBUG,
	Z0_OPTYPE_REG_TEST,
	Z0_OPTYPE_REG_ST,
	Z0_OPTYPE_REG_MM,
	Z0_OPTYPE_REG_XMM,

	Z0_OPTYPE_EMPTY,
	Z0_OPTYPE_ERROR,

	Z0_OPTYPE_AL,
	Z0_OPTYPE_CL,
	Z0_OPTYPE_DL,
	Z0_OPTYPE_BL,
	Z0_OPTYPE_AH,
	Z0_OPTYPE_CH,
	Z0_OPTYPE_DH,
	Z0_OPTYPE_BH,

	Z0_OPTYPE_AX,
	Z0_OPTYPE_CX,
	Z0_OPTYPE_DX,
	Z0_OPTYPE_BX,
	Z0_OPTYPE_SP,
	Z0_OPTYPE_BP,
	Z0_OPTYPE_SI,
	Z0_OPTYPE_DI,

	Z0_OPTYPE_EAX,
	Z0_OPTYPE_ECX,
	Z0_OPTYPE_EDX,
	Z0_OPTYPE_EBX,
	Z0_OPTYPE_ESP,
	Z0_OPTYPE_EBP,
	Z0_OPTYPE_ESI,
	Z0_OPTYPE_EDI,

	Z0_OPTYPE_ES,
	Z0_OPTYPE_CS,
	Z0_OPTYPE_SS,
	Z0_OPTYPE_DS,
	Z0_OPTYPE_FS,
	Z0_OPTYPE_GS,

	Z0_OPTYPE_PTR_BX_SI,
	Z0_OPTYPE_PTR_BX_DI,
	Z0_OPTYPE_PTR_BP_SI,
	Z0_OPTYPE_PTR_BP_DI,
	Z0_OPTYPE_PTR_SI,
	Z0_OPTYPE_PTR_DI,
	Z0_OPTYPE_PTR_BP,
	Z0_OPTYPE_PTR_BX,

	Z0_OPTYPE_PTR_EAX,
	Z0_OPTYPE_PTR_ECX,
	Z0_OPTYPE_PTR_EDX,
	Z0_OPTYPE_PTR_EBX,
	Z0_OPTYPE_PTR_ESP,
	Z0_OPTYPE_PTR_EBP,
	Z0_OPTYPE_PTR_ESI,
	Z0_OPTYPE_PTR_EDI,

	Z0_OPTYPE_ST0,
	Z0_OPTYPE_ST1,
	Z0_OPTYPE_ST2,
	Z0_OPTYPE_ST3,
	Z0_OPTYPE_ST4,
	Z0_OPTYPE_ST5,
	Z0_OPTYPE_ST6,
	Z0_OPTYPE_ST7,

	Z0_OPTYPE_MM0,
	Z0_OPTYPE_MM1,
	Z0_OPTYPE_MM2,
	Z0_OPTYPE_MM3,
	Z0_OPTYPE_MM4,
	Z0_OPTYPE_MM5,
	Z0_OPTYPE_MM6,
	Z0_OPTYPE_MM7,

	Z0_OPTYPE_XMM0,
	Z0_OPTYPE_XMM1,
	Z0_OPTYPE_XMM2,
	Z0_OPTYPE_XMM3,
	Z0_OPTYPE_XMM4,
	Z0_OPTYPE_XMM5,
	Z0_OPTYPE_XMM6,
	Z0_OPTYPE_XMM7,

	Z0_OPTYPE_SCALE2,
	Z0_OPTYPE_SCALE4,
	Z0_OPTYPE_SCALE8,

	Z0_OPTYPE_BYTE_PTR,
	Z0_OPTYPE_WORD_PTR,
	Z0_OPTYPE_DWORD_PTR,
	Z0_OPTYPE_FWORD_PTR,
	Z0_OPTYPE_QWORD_PTR,
	Z0_OPTYPE_TBYTE_PTR,
	Z0_OPTYPE_NEAR_PTR,
	Z0_OPTYPE_FAR_PTR,

	Z0_OPTYPE_1,
	Z0_OPTYPE_CL_1,

	Z0_OPTYPE_EBX_PTR_1,
	Z0_OPTYPE_BX_PTR_1,

	Z0_OPTYPE_CR0,
	Z0_OPTYPE_CR1,
	Z0_OPTYPE_CR2,
	Z0_OPTYPE_CR3,
	Z0_OPTYPE_CR4,
	Z0_OPTYPE_CR5,
	Z0_OPTYPE_CR6,
	Z0_OPTYPE_CR7,

	Z0_OPTYPE_DR0,
	Z0_OPTYPE_DR1,
	Z0_OPTYPE_DR2,
	Z0_OPTYPE_DR3,
	Z0_OPTYPE_DR4,
	Z0_OPTYPE_DR5,
	Z0_OPTYPE_DR6,
	Z0_OPTYPE_DR7,

	Z0_OPTYPE_TR0,
	Z0_OPTYPE_TR1,
	Z0_OPTYPE_TR2,
	Z0_OPTYPE_TR3,
	Z0_OPTYPE_TR4,
	Z0_OPTYPE_TR5,
	Z0_OPTYPE_TR6,
	Z0_OPTYPE_TR7,

	Z0_OPTYPE_LAST
};

typedef struct Z0_OPERAND
{
	unsigned short type;
	unsigned short ptr;
	unsigned short index;
	unsigned short scale;
	unsigned short base;

	unsigned short segment;

	union
	{
		unsigned char imm8;
		char imm8signed;
		unsigned short imm16;
		unsigned int imm32;

		int rel32;

	} value;

} Z0_OPERAND, *PZ0_OPERAND;

typedef struct MODRM
{
	unsigned char rm:3;
	unsigned char reg:3;
	unsigned char mod:2;
} MODRM;

typedef struct SIB
{
	unsigned char base:3;
	unsigned char index:3;
	unsigned char scale:2;
} SIB;

typedef struct Z0_DISASM_CONTEXT_VOLATILE
{
	unsigned short mnemonic;

	unsigned short optype[Z0_MAX_OPERANDS];
	Z0_OPERAND operand[Z0_MAX_OPERANDS];

	unsigned long flags;

	unsigned short prefix_operand;
	unsigned short prefix_address;
	unsigned short prefix_lock;
	unsigned short prefix_repeat;
	unsigned short prefix_segment;

	unsigned short length;

	MODRM* modrm;
	SIB* sib;

	unsigned char bytes[Z0_MAX_OPCODE_LENGTH];

} Z0_DISASM_CONTEXT_VOLATILE, *PZ0_DISASM_CONTEXT_VOLATILE;

typedef struct Z0_DISASM_CONTEXT
{
	unsigned short mnemonic;

	unsigned short optype[Z0_MAX_OPERANDS];
	Z0_OPERAND operand[Z0_MAX_OPERANDS];

	unsigned long flags;

	unsigned short prefix_operand;
	unsigned short prefix_address;
	unsigned short prefix_lock;
	unsigned short prefix_repeat;
	unsigned short prefix_segment;

	unsigned short length;

	MODRM* modrm;
	SIB* sib;

	unsigned char bytes[Z0_MAX_OPCODE_LENGTH];

	union
	{
		void* addr;
		unsigned char* addr_ptr;
	};

	unsigned short mode;

	Z0_DISASM finish;

} Z0_DISASM_CONTEXT, *PZ0_DISASM_CONTEXT;

typedef struct Z0_OPCODE_TABLE
{
	Z0_DISASM process_handler;
	unsigned short mnemonic;
	unsigned short optype[Z0_MAX_OPERANDS];
	unsigned long flags;

} Z0_OPCODE_TABLE, *PZ0_OPCODE_TABLE;

Z0_STATUS disasm(PZ0_DISASM_CONTEXT context);

extern char* translate_mnemonic[];
extern char* translate_optype[];

int mnemonic_selfcheck(void);
int optype_selfcheck(void);
